services:
  app:
    build:
      context: .
      target: dev-build
      dockerfile: Dockerfile.dev
      args:
        DOCKER_USER: ${DOCKER_USER:-root}
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    stdin_open: true
    tty: true
    command: mix phx.server
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: postgres:13.5-alpine # as used in production deployment
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 54321:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
