name: Fly Deploy

on:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        required: true

jobs:
  deploy:
      name: staging
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --app adoptoposs-staging --config ./fly.staging.toml --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
